import type { Lang } from '@/lib/i18n'

type L = Record<Lang, string>

export type PreventionItem = {
  id: number
  icon: string
  title: L
  description: L
}

const i = (id: number, icon: string, title: L, description: L): PreventionItem => ({ id, icon, title, description })

/** Sections du module — avant / pendant / après + bâtiment non parasismique */
export const preventionSections = {
  /** ANVAN — préparation générale */
  avant: [
    i(21, '📋', { fr: 'Plan familial d\'urgence', kr: 'Plan ijan pou fanmi', en: 'Family emergency plan', es: 'Plan de emergencia familiar' }, { fr: 'Point de rassemblement, contacts, qui récupère les enfants. Écrivez et partagez.', kr: 'Pwen randevou, kontak, ki moun ki prale pitit yo. Ekri epi pataje.', en: 'Meeting point, contacts, who picks up children. Write and share.', es: 'Punto de encuentro, contactos, quién recoge a los niños. Escríbelo y compártelo.' }),
    i(22, '📍', { fr: 'Zones sûres identifiées', kr: 'Zòn ki an sekirite idantifye', en: 'Identified safe zones', es: 'Zonas seguras identificadas' }, { fr: '2 endroits par pièce : sous table solide, coin intérieur loin des fenêtres.', kr: '2 kote pa chanm : anba tab solid, kwen andedan lwen fenèt.', en: '2 spots per room: under sturdy table, interior corner away from windows.', es: '2 lugares por habitación: bajo mesa sólida, rincón interior lejos de ventanas.' }),
    i(23, '🪑', { fr: 'Fixer meubles lourds', kr: 'Fè meb lou yo solid', en: 'Secure heavy furniture', es: 'Fijar muebles pesados' }, { fr: 'Armoires, réfrigérateur, chauffe-eau : attaches murales. Évite chutes sur lits.', kr: 'Amwa, frijidè, chofè : mare yo sou mi. Evite yo tonbe sou kabann.', en: 'Wardrobes, fridge, water heater: wall anchors. Prevent falls onto beds.', es: 'Armarios, nevera, calentador: anclajes. Evita caídas sobre camas.' }),
    i(24, '🔧', { fr: 'Coupe gaz / électricité', kr: 'Koupe gaz / elektrisite', en: 'Gas / power shutoff', es: 'Corte de gas / electricidad' }, { fr: 'Savoir où couper gaz, eau et électricité. Toute la famille doit connaître.', kr: 'Konnen ki kote pou koupe gaz, dlo, elektrisite. Tout fanmi dwe konnen.', en: 'Know where to shut off gas, water and power. Whole family must know.', es: 'Sepa dónde cortar gas, agua y electricidad. Toda la familia debe saberlo.' }),
    i(25, '📄', { fr: 'Documents et contacts', kr: 'Dokiman ak kontak', en: 'Documents and contacts', es: 'Documentos y contactos' }, { fr: 'Copies actes, assurance, médecin — pochette étanche près de la sortie.', kr: 'Kopi akt, asirans, doktè — pòch etanch bò pòt sorti.', en: 'Copies of deeds, insurance, doctor — waterproof pouch near exit.', es: 'Copias de actas, seguro, médico — bolsa impermeable cerca de la salida.' }),
    i(26, '🏃', { fr: 'Exercice annuel Bese-Pwoteje-Kenbe', kr: 'Egzèsis Bese-Pwoteje-Kenbe chak ane', en: 'Annual Drop-Cover-Hold drill', es: 'Simulacro anual Agáchate-Cúbrete' }, { fr: 'À l\'école, au travail, à la maison. Automatisez les gestes avant le séisme.', kr: 'Lekòl, travay, kay. Otomatize jès yo anvan tranblemanntè.', en: 'At school, work, home. Automate actions before the earthquake.', es: 'En escuela, trabajo, hogar. Automatiza los gestos antes del sismo.' }),
    i(27, '📻', { fr: 'Source d\'information fiable', kr: 'Sous enfòmasyon serye', en: 'Reliable information source', es: 'Fuente de información fiable' }, { fr: 'Radio à piles, alertes SMS, groupes communautaires. Pas les rumeurs.', kr: 'Radyo ak pil, SMS alèt, gwoup kominotè. Pa rime.', en: 'Battery radio, SMS alerts, community groups. Not rumors.', es: 'Radio a pilas, alertas SMS, grupos comunitarios. No rumores.' }),
    i(28, '🏘️', { fr: 'Réseau voisinage', kr: 'Rezo vwazenaj', en: 'Neighborhood network', es: 'Red de vecinos' }, { fr: 'Identifiez personnes âgées, enfants seuls. Plan d\'entraide local.', kr: 'Idantifye granmoun, timoun pou kont yo. Plan ede youn lòt.', en: 'Identify elderly, children alone. Local mutual aid plan.', es: 'Identifique ancianos, niños solos. Plan de ayuda mutua.' }),
  ],
  /** ANVAN — bâtiment NON parasismique (majorité en Haïti) */
  avant_np: [
    i(31, '🏚️', { fr: 'Connaître le type de bâtiment', kr: 'Konnen kalite bilding', en: 'Know your building type', es: 'Conocer tipo de edificio' }, { fr: 'Béton non armé, étages ajoutés, PAU : assumez vulnérabilité élevée jusqu\'à preuve du contraire.', kr: 'Beton san fè, etaj ajoute, PAU : sipoze li trè vilnerab.', en: 'Unreinforced concrete, added floors, PAU: assume high vulnerability.', es: 'Concreto sin refuerzo, pisos añadidos: asuma alta vulnerabilidad.' }),
    i(32, '🔍', { fr: 'Repérer fissures en diagonale', kr: 'Chèche fisè diagonal', en: 'Spot diagonal cracks', es: 'Detectar grietas diagonales' }, { fr: 'Sur murs porteurs = signe de stress structurel. Faites évaluer avant le prochain choc.', kr: 'Sou mi sipò = siyal estrès estrikti. Fè evalye anvan pwochen chòk.', en: 'On load-bearing walls = structural stress. Get assessed before next shock.', es: 'En muros portantes = estrés estructural. Evalúe antes del próximo sismo.' }),
    i(33, '🚫', { fr: 'Ne pas ajouter d\'étage sans ingénieur', kr: 'Pa ajoute etaj san enjenyè', en: 'No added floors without engineer', es: 'No añadir pisos sin ingeniero' }, { fr: 'Cause majeure d\'effondrements 2010 : surcharge sur structure non calculée.', kr: 'Gwo koz tonbe 2010 : twò chaj sou estrikti ki pa kalkile.', en: 'Major 2010 collapse cause: overload on uncalculated structure.', es: 'Causa mayor de colapsos 2010: sobrecarga sin cálculo estructural.' }),
    i(34, '🛏️', { fr: 'Dormir au rez-de-chaussée si possible', kr: 'Dòmi anba kay si posib', en: 'Sleep on ground floor if possible', es: 'Dormir en planta baja si es posible' }, { fr: 'Dans bâtiment fragile, les étages supérieurs s\'effondrent en premier.', kr: 'Nan bilding fèb, etaj anwo tonbe an premye.', en: 'In fragile buildings, upper floors collapse first.', es: 'En edificios frágiles, los pisos superiores colapsan primero.' }),
    i(35, '⚖️', { fr: 'Éviter charges lourdes en hauteur', kr: 'Evite chaj lou anlè', en: 'Avoid heavy loads up high', es: 'Evitar cargas pesadas arriba' }, { fr: 'Citernes, réservoirs, débris sur toiture fragile : risque d\'effondrement local.', kr: 'Siven, rezèvwa, debi sou twat fèb : risk tonbe.', en: 'Tanks, debris on weak roofs: local collapse risk.', es: 'Tanques, escombros en techos débiles: riesgo de colapso.' }),
    i(36, '🩺', { fr: 'Passer le diagnostic SisAyiti', kr: 'Fè dyagnostik SisAyiti', en: 'Run SisAyiti diagnostic', es: 'Hacer diagnóstico SisAyiti' }, { fr: '5 questions pour estimer vulnérabilité et priorités de renforcement.', kr: '5 kesyon pou evalye vilnerabilite ak priyorite ranfòsman.', en: '5 questions to estimate vulnerability and reinforcement priorities.', es: '5 preguntas para estimar vulnerabilidad y prioridades.' }),
    i(37, '🏗️', { fr: 'Renforcement progressif', kr: 'Ranfòsman piti piti', en: 'Gradual reinforcement', es: 'Refuerzo progresivo' }, { fr: 'Colonnes, ceintures béton, liaisons toit-mur : avec professionnel qualifié.', kr: 'Kolòn, sèl beton, lyen twati-mi : ak pwofesyonèl kalifye.', en: 'Columns, concrete belts, roof-wall ties: with qualified professional.', es: 'Columnas, cintas de concreto, amarres techo-muro: con profesional.' }),
    i(38, '🗺️', { fr: 'Repérer pièces les plus faibles', kr: 'Make chanm ki pi fèb yo', en: 'Map weakest rooms', es: 'Identificar habitaciones más débiles' }, { fr: 'Grands vides (magasin RDC), balcons, angles de murs en L : évitez-y le séjour prolongé.', kr: 'Gwo espas (magazen rez-de-chaussee), balkon, kwen mi : evite rete lontan.', en: 'Large openings (ground shops), balconies, L-corners: avoid prolonged stay.', es: 'Grandes aberturas (tiendas PB), balcones, esquinas en L: evite permanencia.' }),
  ],
  /** PENDANT — gestes Bese-Pwoteje-Kenbe */
  pendant: [
    i(1, '⬇️', { fr: 'Baissez-vous immédiatement', kr: 'Bese tèt ou imedyatman', en: 'Drop down immediately', es: 'Agáchate de inmediato' }, { fr: 'Évitez les chutes d\'objets. Accroupissez-vous — ne vous allongez pas.', kr: 'Evite objè ki tonbe. Akwoupi — pa kouche plat.', en: 'Avoid falling objects. Crouch — do not lie flat.', es: 'Evita objetos cayendo. Agáchate — no te acuestes.' }),
    i(2, '🛡️', { fr: 'Protégez tête et nuque', kr: 'Pwoteje tèt ak kou', en: 'Protect head and neck', es: 'Protege cabeza y cuello' }, { fr: 'Mains, coussin, sac à dos. La tête est la priorité absolue.', kr: 'Men, kousen, sak do. Tèt se priyorite absoli.', en: 'Hands, cushion, backpack. Head is absolute priority.', es: 'Manos, cojín, mochila. La cabeza es prioridad absoluta.' }),
    i(3, '🚫', { fr: 'Ne courez pas', kr: 'Pa kouri', en: 'Do not run', es: 'No corras' }, { fr: 'Couloirs, escaliers et sorties = zones de chute et collision.', kr: 'Kouloir, eskalye, sorti = zòn tonbe ak kolizyon.', en: 'Hallways, stairs and exits = fall and collision zones.', es: 'Pasillos, escaleras y salidas = zonas de caída.' }),
    i(4, '🪑', { fr: 'Sous table ou bureau solide', kr: 'Anba tab oswa biwo solid', en: 'Under sturdy table or desk', es: 'Bajo mesa o escritorio sólido' }, { fr: 'Tenez-vous des pieds. Si pas de table : contre mur intérieur porteur.', kr: 'Kenbe pye tab la. Si pa gen tab : kont mi andedan sipò.', en: 'Hold table legs. If no table: against interior load-bearing wall.', es: 'Sujeta las patas. Sin mesa: contra muro interior portante.' }),
    i(5, '⚠️', { fr: 'Ne sortez PAS pendant les secousses', kr: 'PA SOTI pandan sekou yo', en: 'Do NOT exit during shaking', es: 'NO salgas durante la sacudida' }, { fr: 'Tuiles, briques et vitres tombent des façades. Plus sûr sous abri.', kr: 'Twal, brik, vè tonbe sou façade. Pi an sekirite anba abri.', en: 'Tiles, bricks, glass fall from facades. Safer under cover.', es: 'Tejas, ladrillos, vidrio caen de fachadas. Más seguro bajo cobertura.' }),
    i(6, '🪟', { fr: 'Loin des fenêtres et verrières', kr: 'Lwen fenèt ak vè', en: 'Away from windows and glass', es: 'Lejos de ventanas y vidrios' }, { fr: 'Éclats de verre = blessures graves. Tournez le dos aux vitres.', kr: 'Moso vè = gwo blesi. Vire do ou bay vit yo.', en: 'Glass shards = serious injuries. Turn back to glass.', es: 'Fragmentos de vidrio = lesiones graves.' }),
    i(7, '💪', { fr: 'Kenbe jusqu\'à la fin', kr: 'Kenbe jiskaske fini', en: 'Hold on until it ends', es: 'Agárrate hasta el final' }, { fr: 'Attendez la fin des secousses ET des répliques possibles avant de bouger.', kr: 'Tann sekou yo fini AK replik posib anvan ou bouje.', en: 'Wait for shaking AND possible aftershocks to end before moving.', es: 'Espera a que cese la sacudida Y posibles réplicas.' }),
    i(8, '💨', { fr: 'Respirez, restez calme', kr: 'Respire, rete kalm', en: 'Breathe, stay calm', es: 'Respira, mantén la calma' }, { fr: 'La panique tue : erreurs de sortie, bousculade. Parlez aux enfants.', kr: 'Panik touye : erè, pile moun. Pale ak timoun yo.', en: 'Panic kills: exit mistakes, stampedes. Talk to children.', es: 'El pánico mata: errores de salida. Habla a los niños.' }),
  ],
  /** PENDANT — bâtiment NON parasismique */
  pendant_np: [
    i(41, '🏢', { fr: 'Étages supérieurs = danger maximal', kr: 'Etaj anwo = pi gwo danje', en: 'Upper floors = maximum danger', es: 'Pisos superiores = máximo peligro' }, { fr: 'Si vous y êtes : bese intérieur, ne tentez PAS de descendre l\'escalier.', kr: 'Si ou la : bese andedan, pa eseye desann eskalye a.', en: 'If there: drop indoors, do NOT try stairs.', es: 'Si estás ahí: agáchate adentro, NO bajes escaleras.' }),
    i(42, '🪜', { fr: 'Évitez cages d\'escalier', kr: 'Evite eskalye yo', en: 'Avoid stairwells', es: 'Evita escaleras' }, { fr: 'Escaliers et paliers s\'effondrent souvent en béton non armé.', kr: 'Eskalye ak palye tonbe souvan nan beton san fè.', en: 'Stairs and landings often collapse in unreinforced concrete.', es: 'Escaleras colapsan a menudo en concreto sin refuerzo.' }),
    i(43, '🏪', { fr: 'Rez-de-chaussée commercial (soft story)', kr: 'Rez-de-chaussee komèsyal', en: 'Commercial ground floor (soft story)', es: 'Planta baja comercial' }, { fr: 'Colonnes fines + grand vide : fuyez latéralement si déjà dehors ; sinon bese loin des colonnes.', kr: 'Kolòn mens + gwo espas : si deyò ale kote ki pi lwen ; sinon bese lwen kolòn.', en: 'Thin columns + large void: if outside move away; else drop away from columns.', es: 'Columnas finas + gran vacío: si afuera aléjate; si no, agáchate lejos de columnas.' }),
    i(44, '🧱', { fr: 'Loin des murs de clôture / parpaings', kr: 'Lwen mi kloti / blo', en: 'Away from block walls / fences', es: 'Lejos de muros de bloques' }, { fr: 'Murs de clôture et murs non structurés tombent en premier.', kr: 'Mi kloti ak mi ki pa estrikti tonbe an premye.', en: 'Boundary and non-structural walls fall first.', es: 'Muros perimetrales y no estructurales caen primero.' }),
    i(45, '🏗️', { fr: 'Ne pas se réfugier sous linteau béton', kr: 'Pa kache anba linteau beton', en: 'Do not shelter under concrete lintel', es: 'No refugiarse bajo dintel de concreto' }, { fr: 'Portes et fenêtres en béton non armé : zone de cisaillement, effondrement possible.', kr: 'Pòt ak fenèt beton san fè : zòn ki ka kase.', en: 'Unreinforced door/window frames: shear zone, may collapse.', es: 'Marcos sin refuerzo: zona de corte, puede colapsar.' }),
    i(46, '🌳', { fr: 'Dehors : espace ouvert loin du bâtiment', kr: 'Deyò : espas ouvè lwen bilding', en: 'Outside: open space away from building', es: 'Afuera: espacio abierto lejos del edificio' }, { fr: 'Éloignez-vous de murs, balcons, enseignes. Protégez la tête.', kr: 'Ale lwen mi, balkon, anseyn. Pwoteje tèt ou.', en: 'Move from walls, balconies, signs. Protect head.', es: 'Aléjate de muros, balcones, letreros. Protege la cabeza.' }),
    i(47, '🔔', { fr: 'Balcons et appendices', kr: 'Balkon ak apandi', en: 'Balconies and appendages', es: 'Balcones y anexos' }, { fr: 'Ne vous tenez jamais sur un balcon pendant les secousses.', kr: 'Pa kanpe sou balkon pandan sekou yo.', en: 'Never stand on a balcony during shaking.', es: 'Nunca en un balcón durante la sacudida.' }),
  ],
  /** APRE — premières actions */
  apres: [
    i(48, '🩹', { fr: 'Secourir les blessés proches', kr: 'Ede blesi pre ou', en: 'Help nearby injured', es: 'Ayudar a heridos cercanos' }, { fr: 'Stoppez saignements, ne déplacez pas blessés graves sauf danger imminent.', kr: 'Sispann senyen, pa deplase moun ki grav blesi.', en: 'Stop bleeding, do not move seriously injured unless imminent danger.', es: 'Detén hemorragias, no muevas gravemente heridos salvo peligro.' }),
    i(49, '👟', { fr: 'Chaussures et sortie prudente', kr: 'Soulye ak soti pridan', en: 'Shoes and careful exit', es: 'Zapatos y salida prudente' }, { fr: 'Verre et débris partout. Sortez lentement, main sur mur stable.', kr: 'Vè ak debi tout kote. Soti dousman.', en: 'Glass and debris everywhere. Exit slowly.', es: 'Vidrio y escombros. Sal con cuidado.' }),
    i(50, '🔥', { fr: 'Couper gaz et électricité', kr: 'Koupe gaz ak elektrisite', en: 'Shut off gas and power', es: 'Cortar gas y electricidad' }, { fr: 'Si odeur de gaz ou étincelles : coupez, n\'allumez pas de flamme.', kr: 'Si ou santi gaz oswa wè etensèl : koupe, pa limen dife.', en: 'If gas smell or sparks: shut off, no flames.', es: 'Si huele a gas o chispas: corta, sin llamas.' }),
    i(51, '📻', { fr: 'Écouter autorités et radio', kr: 'Koute otorite ak radyo', en: 'Listen to authorities and radio', es: 'Escuchar autoridades y radio' }, { fr: 'Consignes évacuation, tsunamis, zones à risque. Pas les rumeurs WhatsApp.', kr: 'Konsiy evakyasyon, tsunami, zòn danje. Pa rime WhatsApp.', en: 'Evacuation orders, tsunami, hazard zones. Not WhatsApp rumors.', es: 'Órdenes de evacuación, tsunami. No rumores.' }),
    i(52, '🤝', { fr: 'Aider voisins vulnérables', kr: 'Ede vwazen vilnerab', en: 'Help vulnerable neighbors', es: 'Ayudar vecinos vulnerables' }, { fr: 'Personnes âgées, handicap, enfants seuls. Réseau communautaire vital.', kr: 'Granmoun, andikape, timoun pou kont yo.', en: 'Elderly, disabled, children alone. Community network is vital.', es: 'Ancianos, discapacitados, niños solos.' }),
    i(53, '🌊', { fr: 'Côte : risque tsunami', kr: 'Kòt : risk tsunami', en: 'Coast: tsunami risk', es: 'Costa: riesgo de tsunami' }, { fr: 'Après fort séisme côtier : montez en altitude, loin de la mer (Léogâne, Gonaïves…).', kr: 'Apre gwo sekou sou kòt : monte pi wo, lwen lanmè.', en: 'After strong coastal quake: go uphill, away from sea.', es: 'Tras fuerte sismo costero: sube, aléjate del mar.' }),
    i(54, '📸', { fr: 'Documenter les dégâts', kr: 'Dokimante domaj yo', en: 'Document damage', es: 'Documentar daños' }, { fr: 'Photos pour assurance et aides. Sans vous mettre en danger.', kr: 'Foto pou asirans. San mete tèt ou an danje.', en: 'Photos for insurance and aid. Without risking yourself.', es: 'Fotos para seguro y ayuda. Sin ponerse en riesgo.' }),
    i(55, '⏳', { fr: 'Anticiper les répliques', kr: 'Antisipe replik yo', en: 'Expect aftershocks', es: 'Anticipar réplicas' }, { fr: 'Des répliques pendant des semaines. Gardez kit et plan activés.', kr: 'Replik pandan semèn. Kenbe kit ak plan aktif.', en: 'Aftershocks for weeks. Keep kit and plan active.', es: 'Réplicas por semanas. Mantén kit y plan activos.' }),
  ],
  /** APRE — bâtiment NON parasismique */
  apres_np: [
    i(58, '🚫', { fr: 'Ne réintégrez PAS un bâtiment fissuré', kr: 'PA RANTRE nan bilding ki gen fisè', en: 'Do NOT re-enter cracked building', es: 'NO reingresar edificio agrietado' }, { fr: 'Fissures diagonales, murs bombés : effondrement possible aux répliques.', kr: 'Fisè diagonal, mi ki bombe : ka tonbe nan replik.', en: 'Diagonal cracks, bulging walls: may collapse in aftershocks.', es: 'Grietas diagonales, muros abombados: puede colapsar.' }),
    i(59, '🏷️', { fr: 'Attendre inspection professionnelle', kr: 'Tann enspeksyon pwofesyonèl', en: 'Wait for professional inspection', es: 'Esperar inspección profesional' }, { fr: 'Seul un ingénieur peut certifier la réoccupation. Tag rouge = danger.', kr: 'Sèlman enjenyè ka di ou ka rantre. Mak wouj = danje.', en: 'Only an engineer can certify re-occupancy. Red tag = danger.', es: 'Solo un ingeniero puede certificar reocupación.' }),
    i(60, '⚠️', { fr: 'Signes d\'effondrement imminent', kr: 'Siyal bilding ap tonbe', en: 'Imminent collapse signs', es: 'Señales de colapso inminente' }, { fr: 'Cracking audible, étages penchés, poudre de béton : évacuez immédiatement.', kr: 'Bri ki fann, etaj ki bese, poud beton : evakye imedyatman.', en: 'Cracking sounds, leaning floors, concrete dust: evacuate immediately.', es: 'Crujidos, pisos inclinados, polvo: evacúa de inmediato.' }),
    i(61, '🛠️', { fr: 'Ne tentez pas d\'étayer vous-même', kr: 'Pa eseye sipòte poukont ou', en: 'Do not prop up yourself', es: 'No apuntalar por cuenta propia' }, { fr: 'Étaiements improvisés peuvent aggraver l\'effondrement. Appelez experts.', kr: 'Sipò enprovize ka fè bilding tonbe pi mal. Rele ekspè.', en: 'Improvised props may worsen collapse. Call experts.', es: 'Apuntalamientos improvisados empeoran el colapso.' }),
    i(62, '🏠', { fr: 'Hébergement temporaire', kr: 'Lojman tanporè', en: 'Temporary shelter', es: 'Refugio temporal' }, { fr: 'Tente, cour ouverte, centre d\'accueil : préférez à un bâtiment douteux.', kr: 'Tant, lakou, sant akèy : pi bon pase bilding dout.', en: 'Tent, open yard, shelter: prefer over doubtful building.', es: 'Tienda, patio, refugio: mejor que edificio dudoso.' }),
    i(63, '👷', { fr: 'Planifier renforcement', kr: 'Planifye ranfòsman', en: 'Plan reinforcement', es: 'Planificar refuerzo' }, { fr: 'Ceinture béton, colonnes, fondations : avec ingénieur avant la saison des pluies.', kr: 'Sèl beton, kolòn, fondasyon : ak enjenyè anvan sezon lapli.', en: 'Concrete belt, columns, foundations: with engineer before rainy season.', es: 'Cinturón de concreto, columnas: con ingeniero antes de lluvias.' }),
  ],
  kit: [
    i(16, '💧', { fr: 'Eau potable (3 jours)', kr: 'Dlo potab (3 jou)', en: 'Drinking water (3 days)', es: 'Agua potable (3 días)' }, { fr: 'Au moins 3 litres par personne et par jour.', kr: 'Omwen 3 lit pa moun pa jou.', en: 'At least 3 liters per person per day.', es: 'Al menos 3 litros por persona al día.' }),
    i(17, '🥫', { fr: 'Nourriture non périssable', kr: 'Manje ki pa gate', en: 'Non-perishable food', es: 'Alimentos no perecederos' }, { fr: 'Conserves, barres énergétiques, ouvre-boîte manuel.', kr: 'Manje nan bwat, ba enèji, ouvè-bwat manyèl.', en: 'Canned food, energy bars, manual can opener.', es: 'Enlatados, barras energéticas, abrelatas manual.' }),
    i(18, '⚕️', { fr: 'Trousse de premiers soins', kr: 'Kit premye swen', en: 'First aid kit', es: 'Botiquín de primeros auxilios' }, { fr: 'Pansements, antiseptique, médicaments personnels.', kr: 'Pansman, antiseptik, medikaman pèsonèl.', en: 'Bandages, antiseptic, personal medications.', es: 'Vendajes, antiséptico, medicamentos personales.' }),
    i(19, '🔦', { fr: 'Lampe et radio', kr: 'Flach ak radyo', en: 'Flashlight and radio', es: 'Linterna y radio' }, { fr: 'Piles de rechange ou à manivelle.', kr: 'Pil rezèv oswa a manivèl.', en: 'Spare batteries or hand-crank.', es: 'Pilas de repuesto o de manivela.' }),
    i(20, '📣', { fr: 'Sifflet', kr: 'Siflè', en: 'Whistle', es: 'Silbato' }, { fr: 'Pour signaler si vous êtes bloqué sous débris.', kr: 'Pou siyalize si ou bloke anba debi.', en: 'To signal if trapped under debris.', es: 'Para señalar si quedas atrapado.' }),
    i(64, '🧰', { fr: 'Outils de base', kr: 'Zouti debaz', en: 'Basic tools', es: 'Herramientas básicas' }, { fr: 'Pince, corde, gants, masque poussière pour sécuriser après choc.', kr: 'Pens, kod, gan, mask pou sekirite apre chòk.', en: 'Pliers, rope, gloves, dust mask for post-shock safety.', es: 'Alicates, cuerda, guantes, mascarilla.' }),
    i(65, '💵', { fr: 'Espèces et copies', kr: 'Lajan kach ak kopi', en: 'Cash and copies', es: 'Efectivo y copias' }, { fr: 'Argent liquide, photocopies pièces d\'identité en pochette étanche.', kr: 'Lajan kach, kopi pyès idantite nan pòch etanch.', en: 'Cash, ID copies in waterproof pouch.', es: 'Efectivo, copias de identificación impermeables.' }),
  ],
  dangers: [
    i(12, '🧱', { fr: 'Murs de clôture', kr: 'Mi kloti', en: 'Boundary walls', es: 'Muros perimetrales' }, { fr: 'S\'effondrent très facilement. Distance minimale en permanence.', kr: 'Yo tonbe fasilman. Rete lwen tout tan.', en: 'Collapse very easily. Keep minimum distance always.', es: 'Colapsan muy fácilmente. Distancia mínima siempre.' }),
    i(13, '🏔️', { fr: 'Mornes et ravines', kr: 'Mòn ak ravin', en: 'Hillsides and ravines', es: 'Laderas y barrancos' }, { fr: 'Glissements amplifiés par séisme + pluie. Évitez de construire en pente.', kr: 'Glisman ogmante ak tranblemanntè + lapli.', en: 'Landslides amplified by quake + rain. Avoid building on slopes.', es: 'Deslizamientos amplificados por sismo + lluvia.' }),
    i(14, '🌊', { fr: 'Liquéfaction (PAP, côtes)', kr: 'Likefaksyon (Pòtoprens, kòt)', en: 'Liquefaction (PAP, coast)', es: 'Licuefacción (PAP, costa)' }, { fr: 'Sols saturés perdent portance. Fondations affaissées, tuyaux rompus.', kr: 'Tè plen dlo pèdi fòs. Fondasyon afese.', en: 'Saturated soils lose bearing. Foundations sink, pipes break.', es: 'Suelos saturados pierden capacidad portante.' }),
    i(15, '🔥', { fr: 'Incendies secondaires', kr: 'Dife segondè', en: 'Secondary fires', es: 'Incendios secundarios' }, { fr: 'Réchauds charbon, bouteilles gaz, câbles électriques rompus.', kr: 'Recho charbon, boutey gaz, fil elektrisite kase.', en: 'Charcoal stoves, gas bottles, broken electrical wires.', es: 'Estufas de carbón, gas, cables rotos.' }),
    i(66, '🏚️', { fr: 'Bâtiments adjacents fragiles', kr: 'Bilding vwazen ki fèb', en: 'Fragile adjacent buildings', es: 'Edificios adyacentes frágiles' }, { fr: 'Effondrement d\'un voisin peut endommager le vôtre. Gardez distance après choc.', kr: 'Bilding vwazen ka domaje pa ou. Rete lwen apre chòk.', en: 'Neighbor collapse can damage yours. Keep distance after shock.', es: 'Colapso vecino puede dañar el suyo.' }),
  ],
} as const satisfies Record<string, PreventionItem[]>

export type PreventionSectionKey = keyof typeof preventionSections

export const PREVENTION_SECTION_KEYS = Object.keys(preventionSections) as PreventionSectionKey[]

export type PreventionPhase = 'avant' | 'pendant' | 'apres'

export const PHASE_SECTIONS: Record<PreventionPhase, PreventionSectionKey[]> = {
  avant: ['avant', 'avant_np', 'kit', 'dangers'],
  pendant: ['pendant', 'pendant_np'],
  apres: ['apres', 'apres_np'],
}

export function countAllPreventionItems(): number {
  return PREVENTION_SECTION_KEYS.reduce((n, k) => n + preventionSections[k].length, 0)
}

/** Compatibilité ancienne progression (bese/pwoteje/kenbe → pendant) */
export function migratePreventionProgress(raw: Record<string, number[]>): Record<string, number[]> {
  const out = { ...raw }
  const legacy = [...(out.bese ?? []), ...(out.pwoteje ?? []), ...(out.kenbe ?? [])]
  if (legacy.length > 0) {
    out.pendant = [...new Set([...(out.pendant ?? []), ...legacy])]
    delete out.bese
    delete out.pwoteje
    delete out.kenbe
  }
  return out
}
